import Redis from 'ioredis';

export const connection = new Redis({
  host: 'localhost',
  port: 6381,
  maxRetriesPerRequest: null
});

// Queue priorities for weighted job distribution
// High priority: Critical business operations that need immediate processing
// Medium priority: Standard business operations
// Low priority: Background tasks, maintenance, monitoring
export const QUEUE_PRIORITIES = {
  high: [
    // Financial & critical business
    'payment-processor', 'invoice-generator', 'order-fulfillment', 'refund-processor',
    'chargeback-handler', 'fraud-detection', 'subscription-renewer', 'billing-calculator',
    'settlement-processor', 'payout-service', 'tax-calculator', 'commission-calculator',
    'reconciliation', 'gift-card-processor', 'coupon-validator', 'discount-applier',
    // Security critical
    'mfa-verifier', 'token-refresher', 'permission-checker', 'access-logger',
    'ddos-protector', 'firewall-updater', 'security-scanner', 'threat-analyzer',
    // Real-time user facing
    'chat-message', 'push-notification', 'sms-sender', 'webhook-processor',
    'notification-sender', 'alert-processor', 'incident-detector',
  ],
  medium: [
    // Content & media processing
    'image-processing', 'video-encoding', 'file-converter', 'pdf-generator',
    'thumbnail-creator', 'image-optimizer', 'video-thumbnail', 'audio-transcoder',
    'watermark-adder', 'screenshot-service', 'qr-code-generator', 'barcode-generator',
    'certificate-generator', 'document-parser', 'ocr-processor', 'subtitle-generator',
    // Communication
    'email-sender', 'social-media-post', 'content-moderation', 'translation-service',
    // Reports & analytics
    'report-generator', 'data-analytics', 'export-service', 'import-service',
    'chart-generator', 'dashboard-updater', 'kpi-calculator', 'forecast-generator',
    'revenue-reporter', 'variance-analyzer', 'pivot-calculator', 'graph-builder',
    // User management
    'user-onboarding', 'recommendation-engine', 'search-indexer', 'recommendation-updater',
    'achievement-processor', 'badge-assigner', 'level-calculator', 'reward-distributor',
    'referral-tracker', 'loyalty-points', 'leaderboard-updater', 'trending-calculator',
    // Data operations
    'data-migration', 'backup-service', 'restore-service', 'sync-service',
    'etl-pipeline', 'data-cleaner', 'deduplicator', 'enrichment-service',
    'normalizer-service', 'aggregator-service', 'rollup-processor',
  ],
  low: [
    // Monitoring & logging
    'log-aggregator', 'metrics-collector', 'health-checker', 'audit-logger',
    'performance-monitor', 'memory-tracker', 'cpu-monitor', 'disk-monitor',
    'network-monitor', 'bandwidth-tracker', 'latency-checker', 'uptime-monitor',
    'availability-checker', 'sla-monitor', 'profiler-service',
    // Maintenance & cleanup
    'cleanup-service', 'cache-warmer', 'data-retention', 'archive-service',
    'quarantine-manager', 'sanitizer-service', 'garbage-collector',
    // Background processing
    'sitemap-generator', 'seo-analyzer', 'link-checker', 'rss-feed-updater',
    'news-scraper', 'weather-updater', 'stock-price-updater', 'crypto-price-tracker',
    'playlist-updater', 'geocoding-service',
    // Infrastructure
    'replication-service', 'sharding-service', 'load-balancer', 'circuit-breaker',
    'rate-limiter', 'quota-enforcer', 'dns-prefetch', 'preconnect-handler',
    'prefetch-service', 'preload-optimizer', 'resource-hint', 'lazy-loader',
    // Build & deployment (usually scheduled)
    'asset-bundler', 'code-splitter', 'tree-shaker', 'css-minifier', 'js-minifier',
    'html-minifier', 'transpiler-service', 'source-map-generator', 'container-builder',
    'package-builder', 'artifact-uploader', 'registry-sync', 'deployment-orchestrator',
    'rollout-manager', 'rollback-handler', 'canary-controller', 'feature-flag-evaluator',
    // Compliance & validation
    'compliance-checker', 'gdpr-processor', 'license-validator', 'trial-expiry-checker',
    'vulnerability-checker', 'malware-scanner', 'virus-checker', 'penetration-tester',
  ],
} as const;

export const JOB_TYPES = [
  'image-processing',
  'video-encoding',
  'email-sender',
  'data-analytics',
  'report-generator',
  'notification-sender',
  'webhook-processor',
  'file-converter',
  'backup-service',
  'cache-warmer',
  'search-indexer',
  'payment-processor',
  'invoice-generator',
  'order-fulfillment',
  'inventory-sync',
  'user-onboarding',
  'recommendation-engine',
  'fraud-detection',
  'audit-logger',
  'export-service',
  'import-service',
  'data-migration',
  'cleanup-service',
  'health-checker',
  'metrics-collector',
  'log-aggregator',
  'alert-processor',
  'chat-message',
  'push-notification',
  'sms-sender',
  'social-media-post',
  'content-moderation',
  'image-recognition',
  'document-parser',
  'ocr-processor',
  'translation-service',
  'geocoding-service',
  'weather-updater',
  'stock-price-updater',
  'crypto-price-tracker',
  'news-scraper',
  'rss-feed-updater',
  'sitemap-generator',
  'seo-analyzer',
  'link-checker',
  'screenshot-service',
  'pdf-generator',
  'certificate-generator',
  'qr-code-generator',
  'barcode-generator',
  'thumbnail-creator',
  'watermark-adder',
  'image-optimizer',
  'video-thumbnail',
  'audio-transcoder',
  'subtitle-generator',
  'playlist-updater',
  'recommendation-updater',
  'trending-calculator',
  'leaderboard-updater',
  'achievement-processor',
  'badge-assigner',
  'level-calculator',
  'reward-distributor',
  'referral-tracker',
  'subscription-renewer',
  'trial-expiry-checker',
  'license-validator',
  'compliance-checker',
  'gdpr-processor',
  'data-retention',
  'archive-service',
  'restore-service',
  'sync-service',
  'replication-service',
  'sharding-service',
  'load-balancer',
  'circuit-breaker',
  'rate-limiter',
  'quota-enforcer',
  'billing-calculator',
  'tax-calculator',
  'shipping-calculator',
  'discount-applier',
  'coupon-validator',
  'loyalty-points',
  'gift-card-processor',
  'refund-processor',
  'chargeback-handler',
  'reconciliation',
  'settlement-processor',
  'payout-service',
  'commission-calculator',
  'revenue-reporter',
  'forecast-generator',
  'anomaly-detector',
  'pattern-recognizer',
  'sentiment-analyzer',
  'spam-detector',
  'duplicate-detector',
  'conflict-resolver',
  'session-manager',
  'cookie-handler',
  'token-refresher',
  'password-hasher',
  'encryption-service',
  'decryption-service',
  'key-rotator',
  'secret-manager',
  'vault-sync',
  'access-logger',
  'permission-checker',
  'role-assigner',
  'group-manager',
  'team-sync',
  'org-hierarchy-sync',
  'directory-sync',
  'ldap-sync',
  'saml-processor',
  'oauth-handler',
  'sso-validator',
  'mfa-verifier',
  'biometric-processor',
  'device-tracker',
  'location-verifier',
  'ip-validator',
  'geo-blocker',
  'ddos-protector',
  'firewall-updater',
  'security-scanner',
  'vulnerability-checker',
  'penetration-tester',
  'threat-analyzer',
  'malware-scanner',
  'virus-checker',
  'quarantine-manager',
  'sanitizer-service',
  'input-validator',
  'output-encoder',
  'xss-protector',
  'sql-injection-guard',
  'csrf-validator',
  'cors-handler',
  'header-sanitizer',
  'request-validator',
  'response-checker',
  'api-versioner',
  'endpoint-mapper',
  'route-optimizer',
  'url-shortener',
  'deep-link-handler',
  'redirect-manager',
  'canonical-setter',
  'meta-generator',
  'og-tag-creator',
  'schema-markup',
  'structured-data',
  'breadcrumb-generator',
  'pagination-handler',
  'infinite-scroll',
  'lazy-loader',
  'prefetch-service',
  'preload-optimizer',
  'resource-hint',
  'dns-prefetch',
  'preconnect-handler',
  'font-optimizer',
  'css-minifier',
  'js-minifier',
  'html-minifier',
  'asset-bundler',
  'code-splitter',
  'tree-shaker',
  'dead-code-eliminator',
  'polyfill-injector',
  'transpiler-service',
  'source-map-generator',
  'debug-symbol-handler',
  'profiler-service',
  'performance-monitor',
  'memory-tracker',
  'cpu-monitor',
  'disk-monitor',
  'network-monitor',
  'bandwidth-tracker',
  'latency-checker',
  'uptime-monitor',
  'availability-checker',
  'sla-monitor',
  'incident-detector',
  'alert-manager',
  'escalation-handler',
  'on-call-rotator',
  'schedule-manager',
  'calendar-sync',
  'meeting-scheduler',
  'reminder-service',
  'time-tracker',
  'timesheet-processor',
  'attendance-tracker',
  'leave-manager',
  'holiday-calculator',
  'overtime-calculator',
  'payroll-processor',
  'benefits-calculator',
  'expense-tracker',
  'receipt-scanner',
  'invoice-matcher',
  'po-validator',
  'budget-tracker',
  'forecast-updater',
  'variance-analyzer',
  'kpi-calculator',
  'dashboard-updater',
  'widget-renderer',
  'chart-generator',
  'graph-builder',
  'table-formatter',
  'pivot-calculator',
  'aggregator-service',
  'rollup-processor',
  'etl-pipeline',
  'data-cleaner',
  'deduplicator',
  'normalizer-service',
  'enrichment-service',
  'lookup-service',
  'join-processor',
  'split-handler',
  'merge-service',
  'diff-calculator',
  'patch-applier',
  'version-comparator',
  'changelog-generator',
  'release-noter',
  'tag-publisher',
  'artifact-uploader',
  'package-builder',
  'container-builder',
  'image-pusher',
  'registry-sync',
  'deployment-orchestrator',
  'rollout-manager',
  'rollback-handler',
  'canary-controller',
  'blue-green-switcher',
  'feature-flag-evaluator',
  'ab-test-assigner',
  'experiment-tracker',
  'conversion-tracker',
];
